version: '3.8'

services:
  # 1. THE LOAD BALANCER
  nginx:
    image: nginx:alpine
    container_name: moviestream_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./uploads:/app/uploads
    depends_on:
      - frontend
      - backend
    networks:
      - movie_network

  # 2. THE BACKEND (PC1 Node)
  backend:
    build: ./server
    container_name: moviestream_backend
    environment:
      - DB_HOST=192.168.137.132 # PC1 IP (MySQL stays on XAMPP)
      - DB_PORT=3309
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=movie_stream
      - PORT=5000
    networks:
      - movie_network

  # 3. THE FRONTEND
  frontend:
    build: ./client
    container_name: moviestream_frontend
    networks:
      - movie_network

networks:
  movie_network:
    driver: bridge
